name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run basic tests (optional)
        run: |
          echo "No tests yet! Add pytest here"

      - name: Build Docker image
        run: |
          docker build -t pdf-api .

      - name: Login to EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/pdf-ai
            git pull
            docker build -t pdf-ai .
            docker stop pdf-ai-container || true
            docker rm pdf-ai-container || true
            docker run -d -p 8000:8000 --name pdf-ai-container pdf-ai
